service: serverless-puppet-bolt

provider:
  name: aws
  runtime: ruby2.5
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 15
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
  environment:
    HOME: /tmp
    S3_DATA_BUCKET: ${opt:s3_data_bucket}

functions:
  inspec_scan:
    handler: handler.run_bolt
    layers:
      - {Ref: BoltLambdaLayer }

layers:
  bolt:
    path: layer